### PR TITLE
Made compatible with headless execution

### PR DESCRIPTION
**Pull request by djpbarry**
Hey,

First of all thanks for putting together this tool - very useful!

However, I've had issues running this in headless mode, due to...

- The use of the Bio-Formats importer via the run command in the macros
- The use of NonBlockGenericDialogs in the supporting Java code

I've modified both of these and...

- The functionality via the FIJI GUI appears unaffected
- The macros can now be run headlessly

### CODE REVIEW

**Comment by jpylvanainen** [comment]
Hi Dave, 

Thank you for your suggestion. We will review the changes and run some tests with your version before merging.

Cheers, 
Joanna

**Review by brunomsaraiva — COMMENTED** [review]
Everything seems good.

**Comment by NBCS1** [comment]
Hello,
I added the changes and recompiled the plugin locally. The plugin through the GUI is still working but I'm not able to find out how to run it headless.
I simply tried:
`run("time estimate+apply", "Experiment number=001 Select the file(s) to be corrected=/path/to/file/image.tif xy-drift correction=true Projection type=Average Intensity Time averaging (default:100,1 – disables)=1 Maximum expected drift (pixels, 0- auto)=0 Reference frame=previous frame (better for live) Crop output=true z-drift correction=true Projection type=Average Intensity Reslice mode=Top Time averaging (default:100,1 – disables)=1 Reference frame=previous frame (better for live) Extend stack to fit=true Save RAM=false Maximum expected drift (pixels, 0- auto)=0");`

This is only opening the GUI but does not run. How can I bypass the GUI ok button to run it?

Thank you,

Nelson

**Comment by NBCS1** [comment]
> Hey,
> 
> First of all thanks for putting together this tool - very useful!
> 
> However, I've had issues running this in headless mode, due to...
> 
> * The use of the Bio-Formats importer via the run command in the macros
> * The use of NonBlockGenericDialogs in the supporting Java code
> 
> I've modified both of these and...
> 
> * The functionality via the FIJI GUI appears unaffected
> * The macros can now be run headlessly

Hello,

I have been playing all day trying to get it to work headless but could not. Could you indicate how you did it? 
I precise that I recompile locally with your modifications.

Thank you,

Nelson

Edit: It was a matter of path format and space in the variable such as "Average Intensity". Fixed it by 
`"projection_type_xy=[" + "Average Intensity" + "] "`
In case, here is the macro I use to run bot time estimate+apply on a reference channel and time apply on a second channel (from the same stack). I run this macro from subprocess in Python (the rest of my pipeline is in Python). This works on Linux, might have some trouble on Windows with the paths slashes. Not the prettiest but it works!

Python code:
```
def registration(referenceChannelFiles,applyToFiles):
    # Define the parameters in Python
    exp_nro = "001"
    XY_registration = "true"
    projection_type_xy = "Average Intensity"
    time_xy = "1"
    max_xy = "0"
    reference_xy = "previous frame (better for live)"
    crop_output = "true"
    z_registration = "true"
    projection_type_z = "Average Intensity"
    reslice_mode = "Top"
    time_z = "1"
    reference_z = "previous frame (better for live)"
    extend_stack_to_fit = "true"
    ram_conservative_mode = "false"
    max_z = "0"
    files= ",".join(referenceChannelFiles)
    files2=",".join(applyToFiles)
    date=date_fast4Dreg

    # Combine them into a single string separated by semicolons
    
    params = ";".join([exp_nro, files, XY_registration, projection_type_xy, time_xy, max_xy, 
                       reference_xy, crop_output, z_registration, projection_type_z, reslice_mode, 
                       time_z, reference_z, extend_stack_to_fit, ram_conservative_mode, max_z, 
                       files2,date])
    # Construct the ImageJ macro call
    ij_path = "/path/to/imageJ"
    macro_path = "/path/to/Macro/Fast4Dregheadless.ijm"
    cmd = f"{ij_path} -macro {macro_path} \"{params}\""

    # Run the command using subprocess
    subprocess.run(cmd, shell=True)
    subprocess.run(["pkill","ImageJ-linux64",])
```

IJ macro:
```
args = getArgument();

// Split arguments by semicolon (;)
tokens = split(args, ";");

exp_nro = parseInt(tokens[0]);
files = tokens[1];
XY_registration = tokens[2];
projection_type_xy = tokens[3];
time_xy = parseInt(tokens[4]);
max_xy = parseInt(tokens[5]);
reference_xy = tokens[6];
crop_output = tokens[7];
z_registration = tokens[8];
projection_type_z = tokens[9];
reslice_mode = tokens[10];
time_z = parseInt(tokens[11]);
reference_z = tokens[12];
extend_stack_to_fit = tokens[13];
ram_conservative_mode = tokens[14];
max_z = parseInt(tokens[15]);
date=tokens[17]
// Combine them into a single string for the macro
params = "exp_nro=" + exp_nro + " " +
         "files=[" + files + "] " +
         "XY_registration=" + XY_registration + " " +
         "projection_type_xy=[" + projection_type_xy + "] " +
         "time_xy=" + time_xy + " " +
         "max_xy=" + max_xy + " " +
         "reference_xy=[" + reference_xy + "] " +
         "crop_output=" + crop_output + " " +
         "z_registration=" + z_registration + " " +
         "projection_type_z=[" + projection_type_z + "] " +
         "reslice_mode=[" + reslice_mode + "] " +
         "time_z=" + time_z + " " +
         "reference_z=[" + reference_z + "] " +
         "extend_stack_to_fit=" + extend_stack_to_fit + " " +
         "ram_conservative_mode=" + ram_conservative_mode + " " +
         "max_z=" + max_z;

// Run the command
run("time estimate+apply", params);
// Combine them into a single string

files2 = tokens[16];
pathArrayC1 = split(files2, ",");
pathArrayC2 = split(files, ",");

for (i = 0; i < pathArrayC2.length; i++) {
	lastSlash = lastIndexOf(pathArrayC2[i], "/"); 
	// Extract the folder path (everything before the last slash)
	workingFolder=substring(pathArrayC2[i], 0, lastSlash);
	filename =substring(pathArrayC2[i], lastSlash + 1);
	filename=replace(filename, ".tif", "");
	settings_file_path =workingFolder+"//"+filename+"_"+date+"-001//"+filename+"_settings.csv";
	output_folder=workingFolder+"//"+filename+"_"+date+"-001//";
	params2 ="files=[" + pathArrayC1[i] + "] " +
         "settings_file_path=[" + settings_file_path + "] " +
         "results_path=[" + output_folder + "] ";

         run("time apply", params2);
}


run("Quit");

```

**Comment by djpbarry** [comment]
> Hi Dave,
> 
> Thank you for your suggestion. We will review the changes and run some tests with your version before merging.
> 
> Cheers, Joanna

Hi @jpylvanainen,

Could this please be merged now?

Thanks!

**Comment by jpylvanainen** [comment]
Hi Dave, 

Sorry for the delay, I will merge it!

Best,
Joanna

**Pull request merged**
